name: Terraform Destroy Infrastructure

on:
  workflow_dispatch:  # Only manual triggers for safety

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: production  # Optional: add manual approval step

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.2.0

    - name: Terraform Init
      run: terraform init \
          -backend-config="bucket=lade-terraform-bucket" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=us-east-1"

    - name: Terraform Destroy
      env:
        TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      run: terraform destroy -auto-approve -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -input=false
